migrate from drone to GH actions
rancher/confd pull request #13
Opened 2024-05-22 01:15 UTC by slickwarren

example GH Actions run: https://github.com/slickwarren/confd/actions/runs/9183757785

what the releases look like: https://github.com/slickwarren/confd/releases

2024-05-22 15:21 UTC, HarrisonWAffel approved these changes

2024-05-23 16:29 UTC, jiaqiluo requested changes

2024-05-23 16:29 UTC, jiaqiluo commented on .drone.yml
> -      path: /var/run/docker.sock
It looks like `ci` is expected to run on all events. Could you add a workflow that runs `dapper ci` in the event of `pull request` and `merge`?

2024-05-23 19:11 UTC, jiaqiluo requested changes

2024-05-23 19:11 UTC, jiaqiluo commented on .github/workflows/ci.yml
> +      - master
It seems like `release/v0.16` is the default and active branch in this repo. 
```suggestion
      - release/v0.16
```

2024-05-23 21:29 UTC, jiaqiluo approved these changes

2024-05-24 18:28 UTC, merged